version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
