/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as IncomeIndexImport } from './routes/income/index'
import { Route as ExpenseIndexImport } from './routes/expense/index'
import { Route as CategoriesIndexImport } from './routes/categories/index'
import { Route as IncomeCreateIncomeImport } from './routes/income/CreateIncome'
import { Route as ExpenseCreateExpenseImport } from './routes/expense/CreateExpense'
import { Route as CategoriesCreateCategoryImport } from './routes/categories/createCategory'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IncomeIndexRoute = IncomeIndexImport.update({
  path: '/income/',
  getParentRoute: () => rootRoute,
} as any)

const ExpenseIndexRoute = ExpenseIndexImport.update({
  path: '/expense/',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesIndexRoute = CategoriesIndexImport.update({
  path: '/categories/',
  getParentRoute: () => rootRoute,
} as any)

const IncomeCreateIncomeRoute = IncomeCreateIncomeImport.update({
  path: '/income/CreateIncome',
  getParentRoute: () => rootRoute,
} as any)

const ExpenseCreateExpenseRoute = ExpenseCreateExpenseImport.update({
  path: '/expense/CreateExpense',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesCreateCategoryRoute = CategoriesCreateCategoryImport.update({
  path: '/categories/createCategory',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/categories/createCategory': {
      id: '/categories/createCategory'
      path: '/categories/createCategory'
      fullPath: '/categories/createCategory'
      preLoaderRoute: typeof CategoriesCreateCategoryImport
      parentRoute: typeof rootRoute
    }
    '/expense/CreateExpense': {
      id: '/expense/CreateExpense'
      path: '/expense/CreateExpense'
      fullPath: '/expense/CreateExpense'
      preLoaderRoute: typeof ExpenseCreateExpenseImport
      parentRoute: typeof rootRoute
    }
    '/income/CreateIncome': {
      id: '/income/CreateIncome'
      path: '/income/CreateIncome'
      fullPath: '/income/CreateIncome'
      preLoaderRoute: typeof IncomeCreateIncomeImport
      parentRoute: typeof rootRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/expense/': {
      id: '/expense/'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof ExpenseIndexImport
      parentRoute: typeof rootRoute
    }
    '/income/': {
      id: '/income/'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutLazyRoute,
  CategoriesCreateCategoryRoute,
  ExpenseCreateExpenseRoute,
  IncomeCreateIncomeRoute,
  CategoriesIndexRoute,
  ExpenseIndexRoute,
  IncomeIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/categories/createCategory",
        "/expense/CreateExpense",
        "/income/CreateIncome",
        "/categories/",
        "/expense/",
        "/income/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/categories/createCategory": {
      "filePath": "categories/createCategory.tsx"
    },
    "/expense/CreateExpense": {
      "filePath": "expense/CreateExpense.tsx"
    },
    "/income/CreateIncome": {
      "filePath": "income/CreateIncome.tsx"
    },
    "/categories/": {
      "filePath": "categories/index.tsx"
    },
    "/expense/": {
      "filePath": "expense/index.tsx"
    },
    "/income/": {
      "filePath": "income/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
